import { IconType } from "react-icons";

import {
  HiChevronUp,
  HiChevronDown,
  HiChevronRight,
  HiChevronLeft,
  HiArrowUpRight,
  HiOutlineArrowPath,
  HiCheck,
  HiMiniQuestionMarkCircle,
  HiMiniXMark,
  HiOutlineLink,
  HiExclamationTriangle,
  HiInformationCircle,
  HiExclamationCircle,
  HiCheckCircle,
  HiMiniGlobeAsiaAustralia,
  HiEnvelope,
  HiCalendarDays,
  HiClipboard,
  HiPlay,
  HiDocument,
  HiArrowDown,
  HiUsers,
  HiUser,
  HiUserPlus,
  HiUserGroup,
  HiMap,
  HiMapPin,
  HiLink,
  HiCalendar,
  HiStar,
  HiHeart,
  HiBuildingOffice2,
  HiCodeBracket,
  HiMagnifyingGlass,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  FaDiscord,
  FaGithub,
  FaLinkedin,
  FaXTwitter,
  FaYoutube,
  FaCodeBranch,
} from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  chevronUp: HiChevronUp,
  chevronDown: HiChevronDown,
  chevronRight: HiChevronRight,
  chevronLeft: HiChevronLeft,
  refresh: HiOutlineArrowPath,
  arrowUpRight: HiArrowUpRight,
  check: HiCheck,
  helpCircle: HiMiniQuestionMarkCircle,
  infoCircle: HiInformationCircle,
  info: HiInformationCircle,
  warningTriangle: HiExclamationTriangle,
  errorCircle: HiExclamationCircle,
  checkCircle: HiCheckCircle,
  email: HiEnvelope,
  globe: HiMiniGlobeAsiaAustralia,
  play: HiPlay,
  document: HiDocument,
  arrowDown: HiArrowDown,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  close: HiMiniXMark,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaXTwitter,
  clipboard: HiClipboard,
  youtube: FaYoutube,
  users: HiUsers,
  user: HiUser,
  userPlus: HiUserPlus,
  userGroup: HiUserGroup,
  map: HiMap,
  mapPin: HiMapPin,
  link: HiLink,
  star: HiStar,
  heart: HiHeart,
  building: HiBuildingOffice2,
  code: HiCodeBracket,
  search: HiMagnifyingGlass,
  gitFork: FaCodeBranch,
};
